apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T16:37:41Z"
  name: carts-primary
  resourceVersion: "35350"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 75bd200f-62ed-11ea-9aeb-42010a800084
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
