apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-10T16:33:36Z"
  name: carts-canary
  resourceVersion: "34364"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: e3ddfe7b-62ec-11ea-9aeb-42010a800084
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
